package POJO;
// Generated Sep 7, 2022 3:38:09 PM by Hibernate Tools 3.6.0



/**
 * Adminlogz generated by hbm2java
 */
public class Adminlogz  implements java.io.Serializable {


     private Integer id;
     private String unamez;
     private String pwz;

    public Adminlogz() {
    }

    public Adminlogz(String unamez, String pwz) {
       this.unamez = unamez;
       this.pwz = pwz;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUnamez() {
        return this.unamez;
    }
    
    public void setUnamez(String unamez) {
        this.unamez = unamez;
    }
    public String getPwz() {
        return this.pwz;
    }
    
    public void setPwz(String pwz) {
        this.pwz = pwz;
    }




}


