package POJO;
// Generated Sep 7, 2022 3:38:09 PM by Hibernate Tools 3.6.0



/**
 * Branches generated by hbm2java
 */
public class Branches  implements java.io.Serializable {


     private Integer id;
     private String branchname;

    public Branches() {
    }

    public Branches(String branchname) {
       this.branchname = branchname;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBranchname() {
        return this.branchname;
    }
    
    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }




}


