package POJO;
// Generated Sep 7, 2022 3:38:09 PM by Hibernate Tools 3.6.0



/**
 * Cities generated by hbm2java
 */
public class Cities  implements java.io.Serializable {


     private Integer idCity;
     private String district;
     private String city;
     private String statusz;
     private String diliverycost;

    public Cities() {
    }

    public Cities(String district, String city, String statusz, String diliverycost) {
       this.district = district;
       this.city = city;
       this.statusz = statusz;
       this.diliverycost = diliverycost;
    }
   
    public Integer getIdCity() {
        return this.idCity;
    }
    
    public void setIdCity(Integer idCity) {
        this.idCity = idCity;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStatusz() {
        return this.statusz;
    }
    
    public void setStatusz(String statusz) {
        this.statusz = statusz;
    }
    public String getDiliverycost() {
        return this.diliverycost;
    }
    
    public void setDiliverycost(String diliverycost) {
        this.diliverycost = diliverycost;
    }




}


