package POJO;
// Generated Sep 7, 2022 3:38:09 PM by Hibernate Tools 3.6.0



/**
 * Districts generated by hbm2java
 */
public class Districts  implements java.io.Serializable {


     private Integer id;
     private String disnamez;
     private String status;

    public Districts() {
    }

    public Districts(String disnamez, String status) {
       this.disnamez = disnamez;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDisnamez() {
        return this.disnamez;
    }
    
    public void setDisnamez(String disnamez) {
        this.disnamez = disnamez;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


