package POJO;
// Generated Sep 7, 2022 3:38:09 PM by Hibernate Tools 3.6.0



/**
 * Driverdetails generated by hbm2java
 */
public class Driverdetails  implements java.io.Serializable {


     private Integer id;
     private String drivername;
     private String dnicz;
     private String dcontactz;
     private String dpasswordz;
     private String branchz;
     private String statusz;
     private String dregno;
     private String cityz;

    public Driverdetails() {
    }

    public Driverdetails(String drivername, String dnicz, String dcontactz, String dpasswordz, String branchz, String statusz, String dregno, String cityz) {
       this.drivername = drivername;
       this.dnicz = dnicz;
       this.dcontactz = dcontactz;
       this.dpasswordz = dpasswordz;
       this.branchz = branchz;
       this.statusz = statusz;
       this.dregno = dregno;
       this.cityz = cityz;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDrivername() {
        return this.drivername;
    }
    
    public void setDrivername(String drivername) {
        this.drivername = drivername;
    }
    public String getDnicz() {
        return this.dnicz;
    }
    
    public void setDnicz(String dnicz) {
        this.dnicz = dnicz;
    }
    public String getDcontactz() {
        return this.dcontactz;
    }
    
    public void setDcontactz(String dcontactz) {
        this.dcontactz = dcontactz;
    }
    public String getDpasswordz() {
        return this.dpasswordz;
    }
    
    public void setDpasswordz(String dpasswordz) {
        this.dpasswordz = dpasswordz;
    }
    public String getBranchz() {
        return this.branchz;
    }
    
    public void setBranchz(String branchz) {
        this.branchz = branchz;
    }
    public String getStatusz() {
        return this.statusz;
    }
    
    public void setStatusz(String statusz) {
        this.statusz = statusz;
    }
    public String getDregno() {
        return this.dregno;
    }
    
    public void setDregno(String dregno) {
        this.dregno = dregno;
    }
    public String getCityz() {
        return this.cityz;
    }
    
    public void setCityz(String cityz) {
        this.cityz = cityz;
    }




}


