package POJO;
// Generated Sep 18, 2022 12:02:46 PM by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String namez;
     private String nicz;
     private String emailz;
     private String contacttz;
     private String passwrdz;
     private String statusz;

    public Users() {
    }

    public Users(String namez, String nicz, String emailz, String contacttz, String passwrdz, String statusz) {
       this.namez = namez;
       this.nicz = nicz;
       this.emailz = emailz;
       this.contacttz = contacttz;
       this.passwrdz = passwrdz;
       this.statusz = statusz;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamez() {
        return this.namez;
    }
    
    public void setNamez(String namez) {
        this.namez = namez;
    }
    public String getNicz() {
        return this.nicz;
    }
    
    public void setNicz(String nicz) {
        this.nicz = nicz;
    }
    public String getEmailz() {
        return this.emailz;
    }
    
    public void setEmailz(String emailz) {
        this.emailz = emailz;
    }
    public String getContacttz() {
        return this.contacttz;
    }
    
    public void setContacttz(String contacttz) {
        this.contacttz = contacttz;
    }
    public String getPasswrdz() {
        return this.passwrdz;
    }
    
    public void setPasswrdz(String passwrdz) {
        this.passwrdz = passwrdz;
    }
    public String getStatusz() {
        return this.statusz;
    }
    
    public void setStatusz(String statusz) {
        this.statusz = statusz;
    }




}


