package POJO;
// Generated Sep 18, 2022 12:02:46 PM by Hibernate Tools 3.6.0



/**
 * Vehicletypez generated by hbm2java
 */
public class Vehicletypez  implements java.io.Serializable {


     private Integer vehid;
     private String vehtype;
     private String costa;
     private String statuz;

    public Vehicletypez() {
    }

    public Vehicletypez(String vehtype, String costa, String statuz) {
       this.vehtype = vehtype;
       this.costa = costa;
       this.statuz = statuz;
    }
   
    public Integer getVehid() {
        return this.vehid;
    }
    
    public void setVehid(Integer vehid) {
        this.vehid = vehid;
    }
    public String getVehtype() {
        return this.vehtype;
    }
    
    public void setVehtype(String vehtype) {
        this.vehtype = vehtype;
    }
    public String getCosta() {
        return this.costa;
    }
    
    public void setCosta(String costa) {
        this.costa = costa;
    }
    public String getStatuz() {
        return this.statuz;
    }
    
    public void setStatuz(String statuz) {
        this.statuz = statuz;
    }




}


