package POJO;
// Generated Sep 18, 2022 12:02:46 PM by Hibernate Tools 3.6.0



/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String vehiclename;
     private String vehumber;
     private String statusz;
     private String city;
     private String branchz;
     private String availablez;
     private String dname;
     private String dregno;
     private String chassienumber;

    public Vehicle() {
    }

    public Vehicle(String type, String vehiclename, String vehumber, String statusz, String city, String branchz, String availablez, String dname, String dregno, String chassienumber) {
       this.type = type;
       this.vehiclename = vehiclename;
       this.vehumber = vehumber;
       this.statusz = statusz;
       this.city = city;
       this.branchz = branchz;
       this.availablez = availablez;
       this.dname = dname;
       this.dregno = dregno;
       this.chassienumber = chassienumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getVehiclename() {
        return this.vehiclename;
    }
    
    public void setVehiclename(String vehiclename) {
        this.vehiclename = vehiclename;
    }
    public String getVehumber() {
        return this.vehumber;
    }
    
    public void setVehumber(String vehumber) {
        this.vehumber = vehumber;
    }
    public String getStatusz() {
        return this.statusz;
    }
    
    public void setStatusz(String statusz) {
        this.statusz = statusz;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getBranchz() {
        return this.branchz;
    }
    
    public void setBranchz(String branchz) {
        this.branchz = branchz;
    }
    public String getAvailablez() {
        return this.availablez;
    }
    
    public void setAvailablez(String availablez) {
        this.availablez = availablez;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getDregno() {
        return this.dregno;
    }
    
    public void setDregno(String dregno) {
        this.dregno = dregno;
    }
    public String getChassienumber() {
        return this.chassienumber;
    }
    
    public void setChassienumber(String chassienumber) {
        this.chassienumber = chassienumber;
    }




}


